# Generated by Django 3.0.1 on 2020-01-18 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=20)),
                ('nodes', models.CharField(max_length=300)),
                ('link', models.URLField()),
                ('request_mime', models.CharField(choices=[('text', 'text'), ('application/json', 'application/json'), ('multipart/form-data', 'multipart/form-data')], max_length=30)),
                ('request_text', models.TextField()),
                ('request_headers', models.TextField()),
                ('response_pattern_type', models.CharField(choices=[('Text', 'Text'), ('JSON', 'JSON')], max_length=20)),
                ('response_pattern', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
