# Generated by Django 3.0.1 on 2020-01-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='nodes',
            field=models.CharField(choices=[('MSC', 'Moscow'), ('TST1', 'Test1')], max_length=300),
        ),
    ]
