# Generated by Django 3.0.1 on 2020-01-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200120_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='nodes',
            field=models.CharField(blank=True, choices=[('MSC', 'Moscow'), ('TST1', 'Test1')], max_length=300),
        ),
    ]
