# Generated by Django 3.0.1 on 2020-01-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200120_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='nodes',
            field=models.CharField(max_length=300),
        ),
    ]
