# Generated by Django 3.0.1 on 2020-01-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200120_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='request_mime',
            field=models.CharField(choices=[('text', 'text'), ('application/json', 'application/json'), ('multipart/form-data', 'multipart/form-data')], default='application/json', max_length=30),
        ),
    ]
