# Generated by Django 3.0.1 on 2020-01-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200120_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='request_type',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='POST', max_length=20),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='response_pattern_type',
            field=models.CharField(choices=[('Text', 'Text'), ('JSON', 'JSON')], default='JSON', max_length=20),
        ),
    ]
