# Generated by Django 3.0.1 on 2020-01-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200120_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='request_headers',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='request_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='response_pattern',
            field=models.TextField(blank=True),
        ),
    ]
