# Generated by Django 3.0.1 on 2020-01-21 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200120_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
