# Generated by Django 3.0.1 on 2020-01-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userrequest_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
