# Generated by Django 3.0.1 on 2020-01-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userrequest_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='request_mime',
            field=models.CharField(choices=[('TEXT', 'text'), ('JSON', 'application/json'), ('FORM', 'multipart/form-data')], default='JSON', max_length=30),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='response_pattern_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('JSON', 'JSON')], default='JSON', max_length=20),
        ),
    ]
