# Generated by Django 3.0.1 on 2020-01-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200123_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='request_mime',
            field=models.CharField(choices=[('TEXT', 'text'), ('JSON', 'application/json'), ('FORM', 'application/x-www-form-urlencoded')], default='JSON', max_length=30),
        ),
    ]
