# Generated by Django 3.0.1 on 2020-01-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200127_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('hum_read_name', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=20)),
            ],
        ),
    ]
