# Generated by Django 3.0.1 on 2020-02-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_nodesdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='nodes',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='nodes',
            field=models.ManyToManyField(to='api.NodesData'),
        ),
    ]
